[workspace]
resolver = "3"
members = [
    "00 - Template",
    "01 - Secret Entrance",
    "02 - Gift Shop",
    "03 - Lobby",
    "04 - Printing Department",
    "05 - Cafeteria",
    "06 - Trash Compactor",
    "toolbox",
]
