[package]
name = "secret_entrance"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "secret_entrance"

[[bin]]
name = "secret_entrance_2"

[dev-dependencies]
toolbox = { path = "../toolbox" }
