[package]
name = "trash_compactor"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "trash_compactor"

[[bin]]
name = "trash_compactor_2"

[dev-dependencies]
toolbox = { path = "../toolbox" }