[package]
name = "lobby"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "lobby"

[[bin]]
name = "lobby_2"

[dev-dependencies]
criterion = { version = "0.8.0", features = ["html_reports"] }
toolbox = { path = "../toolbox" }

[[bench]]
name = "bench_lobby_2"
harness = false
