[package]
name = "cafeteria"
version = "0.1.0"
edition = "2024"

[dependencies]
toolbox = { path = "../toolbox" }

[[bin]]
name = "cafeteria"

[[bin]]
name = "cafeteria_2"
#
#[dev-dependencies]
#toolbox = { path = "../toolbox" }